
site_name: KKafka

# Meta tags (placed in header)
site_description: KKafka is a thin Kotlin wrapper around the kafka-clients library
site_author: Nico D'Cotta, William Profit
site_url: https://github.com/Kotlin/dokka

# Repository (add link to repository on each page)
repo_name: kkafka
repo_url: https://github.com/kkafkaorg/kkafka
edit_uri: edit/master/docs/src/doc/docs/

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2021 The KKafka team'

# Material theme
theme:
  name: 'material'
  favicon: favicon.svg
  social:
    - type: 'github'
      link: 'https://github.com/kkafkaorg/kkafka'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences

#nav:
#  - Home: index.md
#  - API Reference: "generated/index.html"


extra_javascript:
  - expand_navigation.js
  - api_reference_button.js

extra_css:
  - colours.css
