name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Gradle check and docs render
        env:
          VARIABLE: VALUE
        with:
          job-id: jdk8
          arguments: --no-daemon build mkdocsBuild
          gradle-version: wrapper

      - uses: codecov/codecov-action@v1
        with:
          files: ./build/reports/jacoco/report.xml
          name: codecov-kkafka
          fail_ci_if_error: true
          verbose: false
