name: Check

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: Gradle Dokka and MkDocs render
        env:
          VARIABLE: VALUE
        with:
          job-id: jdk11
          arguments: --no-daemon mkdocsBuild
          gradle-version: wrapper
      - uses: crazy-max/ghaction-github-pages@v2
        name: Github pages depoy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: docs/build/mkdocs
